name: Integration Tests CI

on:
  # Triggers the workflow on any pull request and push to develop
  push:
    branches: [ develop ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  integration-tests:
    name: Integration Tests
    runs-on: macos-15

    concurrency:
      # When running on develop, use the sha to allow all runs of this workflow to run concurrently.
      # Otherwise only allow a single run of this workflow on each branch, automatically cancelling older runs.
      group: ${{ github.ref == 'refs/heads/develop' && format('tests-integration-develop-{0}', github.sha) || format('tests-integration-{0}', github.ref) }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2

      # Common cache
      # Note: GH actions do not support yaml anchor yet. We need to duplicate this for every job
      - uses: actions/cache@v4
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      # Cache for python env for Synapse
      - name: Set up Python 3.13
        uses: actions/setup-python@v2
        with:
          python-version: 3.13
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      # Set up a Synapse server
      - name: Start synapse server
        uses: michaelkaye/setup-matrix-synapse@v1.0.5
        with:
          uploadLogs: true
          httpPort: 8080
          disableRateLimiting: true

      # Common setup
      # Note: GH actions do not support yaml anchor yet. We need to duplicate this for every job
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      # Main step
      - name: Integration tests
        run: bundle exec fastlane test testplan:AllWorkingTests

      # Store artifacts
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report.html
          path: build/test/report.html
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report.junit
          path: build/test/report.junit
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: MatrixSDK-macOS.xcresult
          path: build/test/MatrixSDK-macOS.xcresult/

      # Upload coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
